feat: weak sup. for weakly supervised dataset
EdAbati/fsdl-2022-weak-supervision-project pull request #6
Opened 2022-09-29 10:29 UTC by bergr7

Weak supervision code for weakly supervised ag news datataset.

Note I'm still trying to figure out how to share Rubrix's dataset and rules.

2022-09-29 13:08 UTC, alekshiidenhovi approved these changes
Fine to merge by me, we can create a separate PR for sharing the dataset and rules, when that is figured out.

2022-09-30 07:57 UTC, EdAbati commented
Hey @bergr7 ,
is the error that you mentioned in Discord present in this notebook too?

2022-09-30 09:03 UTC, EdAbati requested changes
Hey @bergr7 all looks good! :)

I fixed a small thing in the Dockerfile (it was not copying requirements before)
Waiting for @diegoquintanav to fix the docker-compose and then we can merge.

Side question, why are we using a validation set with the original labels?
One may have removed the labels from the entire `'train'` set, added labels using weak supervision and only _then_ split between train and validation. In this case, the 'test' set would have been the only one with original labels. Maybe we can include a couple of lines in the notebook/readme explaining this decision?

2022-09-30 09:03 UTC, EdAbati commented on docker-compose.yml
> +    driver: bridge
@diegoquintanav there seems to be an error here. Please check CI log

2022-09-30 14:07 UTC, bergr7 commented on docker-compose.yml
> +    driver: bridge
> Side question, why are we using a validation set with the original labels?
> One may have removed the labels from the entire 'train' set, added labels using weak supervision and only then split between train and validation. In this case, the 'test' set would have been the only one with original labels. Maybe we can include a couple of lines in the notebook/readme explaining this decision?

If I'm not wrong this is explained in the notebook. Of course, you can go ahead and create LFs without a single label. However, you won't be able to measure how good your LFs could be. This means you need significant domain expertise or build it buy expending quite a bit of time on inspection of the data. In a real-world scenario, I'd hand-label a validation set and a test set. I would use the validation set to create the LFs and the test set to test the final model and make sure it generalises. That's why we are using the gold labels in the validation set.

2022-09-30 14:23 UTC, bergr7 commented
> Hey @bergr7 , is the error that you mentioned in Discord present in this notebook too?

Yes, I need to push the revised version.

2022-09-30 15:03 UTC, EdAbati commented on docker-compose.yml
> +    driver: bridge
> If I'm not wrong this is explained in the notebook.
Apologies I didn't understand from the notebook that the goal was to measure the quality of the LFs. It makes more sense now! :) Maybe can you add this comment in the notebook in the paragraph `Splits`?

2022-09-30 16:09 UTC, diegoquintanav commented on docker-compose.yml
> +    driver: bridge
> 

Why do you think there is an error here?

2022-09-30 16:11 UTC, diegoquintanav commented on docker-compose.yml
> +    driver: bridge
Ok, I had two `networks` in the docker-compose file, so I merged them into one.

2022-10-01 15:03 UTC, diegoquintanav commented
can we get eyes on this so we can merge this PR?

2022-10-02 15:19 UTC, EdAbati commented
@diegoquintanav waiting for @bergr7 to push the fixed Jupiter notebook and the I will review

2022-10-03 19:11 UTC, bergr7 commented
@EdAbati @diegoquintanav Pushed the fixes. Sorry for the delay.

2022-10-03 20:42 UTC, EdAbati approved these changes

2022-10-03 20:43 UTC, merged